=== krankos/XML-Schema-example/schema.xsd
<!-- xml schema -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:attribute
    name="subtitle" type="xsd:string"/>


    <!-- Global elements -->
    <xsd:element name="title" type="Title"/>

    <xsd:element name="author" type="xsd:string"/>
    <xsd:element name="opinion" type="xsd:string"/>

    <xsd:complexType name="Title">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute ref="subtitle" use="optional"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>


    <!-- bookType definition -->
    <xsd:complexType name="bookType">
        <xsd:sequence>
            <xsd:element ref="title"/>
            <xsd:element ref="author" maxOccurs="unbounded"/>
            <xsd:element name="tomes" type="tomesType"/>
            <xsd:element name="infosEdition" type="editionType"/>
            <xsd:element ref="opinion" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
    <!-- tomesType definition -->
    <xsd:complexType name="tomesType">
        <xsd:sequence>
            <xsd:element name="tome" type="tomeType" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <!-- tomeType definition -->
    <xsd:complexType name="tomeType">
        <xsd:attribute name="pages" type="xsd:string" use="required"/>
        <xsd:attribute ref="subtitle" use="optional"/>
    </xsd:complexType>

    <!-- editionType definition -->
    <xsd:complexType name="editionType">
        <xsd:sequence>
            <xsd:element name="editor" type="xsd:string"/>
            <xsd:element name="location" type="xsd:string"/>
            <xsd:element name="print" type="xsd:string"/>
            <xsd:element name="isbn" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- articleType definition -->
    <xsd:complexType name="articleType">
        <xsd:sequence>
            <xsd:element ref="title"/>
            <xsd:element ref="author" maxOccurs="unbounded"/>
            <xsd:element name="infosPublication" type="publicationType"/>
            <xsd:element ref="opinion" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- publicationType definition -->
    <xsd:complexType name="publicationType">
        <xsd:sequence>
            <xsd:element name="journal" type="Journal"/>
            <xsd:element name="pages" type="xsd:string"/>
            <xsd:element name="number" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="year" type="Year" default="unknown"/>
    </xsd:complexType>

    <xsd:complexType name="Journal">
        <xsd:attribute name="name" type="xsd:string" default="Feuille de Choux"/>
    </xsd:complexType>

    <!-- Year type -->
    <xsd:simpleType name="Year">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="2000"/>
            <xsd:enumeration value="2001"/>
            <xsd:enumeration value="2002"/>
            <xsd:enumeration value="before_2000"/>
            <xsd:enumeration value="unknown"/>
        </xsd:restriction>
    </xsd:simpleType>


    <!-- bibiliography element -->
    <xsd:element name="bibliography">
        <xsd:complexType>
            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                <xsd:element
                name="book" type="bookType"/>
                <!-- <xsd:element ref="book"></xsd:element> book is a global element -->

                <xsd:element name="article" type="articleType"/>
            </xsd:choice>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== krankos/XML-Schema-example/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<bibliography xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">

    <book>
        <title>Le Seigneur des Anneaux</title>
        <author>J.R.R. Tolkien</author>
        <tomes>
            <tome>
                <pages>1000</pages>
            </tome>
            <tome>
                <pages>1000</pages>
            </tome>
            <tome>
                <pages>1000</pages>
            </tome>
        </tomes>
        <infosEdition>
            <editor>Delcourt</editor>
            <location>Paris</location>
            <print>2000</print>
            <isbn>978-2-7560-1079-8</isbn>
        </infosEdition>
        <opinion>Un chef d'oeuvre</opinion>
    </book>

    <article>
        <title>Le Seigneur des Anneaux</title>
        <author>J.R.R. Tolkien</author>
        <infosPublication>
            <journal>Le Monde</journal>
            <pages>1-10</pages>
            <year>1980</year>
            <number>555</number>
        </infosPublication>
        <opinion>Un chef d'oeuvre</opinion>
    </article>

</bibliography>
